try:
    import bpy
except Exception:
    bpy = None


LANGUAGE_ALIASES = {
    "en_US": "en_US",
    "zh_CN": "zh_HANS",
    "zh_HANS": "zh_HANS",
    "zh_TW": "zh_HANT",
    "zh_HANT": "zh_HANT",
    "ja_JP": "ja_JP",
}


TRANSLATIONS = {
    "zh_HANS": {
        "Basic Language Switching": "基础语言切换",
        "Advanced: Bilingual Language Packs": "高级：双语语言包",
        "Experimental: Region Scope": "实验性：区域范围",
        "Enable Experimental Region Scope": "启用实验性区域范围",
        "Experimental scope: disabled": "实验性范围：已关闭",
        "When disabled, bilingual pack installation uses the default full scope.": "关闭时，双语包安装将使用默认全量范围。",
        "Install / Update Bilingual Packs": "安装/更新双语语言包",
        "Uninstall Bilingual Packs": "卸载双语语言包",
        "Language 1": "语言 1",
        "Language 2": "语言 2",
        "Manage Languages...": "管理语言...",
        "Add Default Languages": "添加默认语言",
        "Switch Language": "切换语言",
        "Open Preferences": "打开偏好设置",
        "Add Language": "添加语言",
        "Add a language to the top-bar switcher": "添加语言到顶部栏切换器",
        "Remove Language": "移除语言",
        "Move Language": "移动语言",
        "Install Bilingual Language Pack": "安装双语语言包",
        "Uninstall Bilingual Language Pack": "卸载双语语言包",
        "Node / Shader / Geometry Nodes": "节点 / 着色器 / 几何节点",
        "Material / Texture": "材质 / 纹理",
        "Animation / Rigging": "动画 / 绑定",
        "Viewport / Navigation": "视图 / 导航",
        "Modeling / Mesh": "建模 / 网格",
        "Sculpt / Paint": "雕刻 / 绘制",
        "Compositor / VFX": "合成器 / 视觉特效",
        "Render / Lighting": "渲染 / 灯光",
        "Custom Keywords": "自定义关键词",
        "Manage languages shown in the top-bar switcher.": "管理顶部栏切换器中显示的语言。",
        "All available languages are already in favorites": "所有可用语言都已在收藏中",
        "Click button above to add languages": "点击上方按钮添加语言",
        "Favorites: {count}": "收藏：{count}",
        "Installs separate zh_en/en_zh languages into Blender's locale folder.": "将独立的 zh_en/en_zh 语言安装到 Blender 的 locale 文件夹。",
        "Backs up the languages file. Restart Blender after install or uninstall.": "会备份 languages 文件。安装或卸载后请重启 Blender。",
        "Generated bilingual packs are removed automatically when this add-on is disabled.": "禁用此插件时会自动移除已生成的双语语言包。",
        "Affects the next bilingual pack install; it does not change the current language immediately.": "影响下一次双语包安装；不会立即改变当前语言。",
        "Uses exact English labels. Same-name UI labels may still be included.": "使用英文标签精确匹配；同名界面标签仍可能被包含。",
        "Installed manifest: not found": "安装清单：未找到",
        "Installed manifest: unreadable": "安装清单：无法读取",
        "Installed manifest: Blender {version}, {count} keywords": "安装清单：Blender {version}，{count} 个关键词",
        "Selected regions: {count} | Custom keywords: {keywords}": "已选区域：{count} | 自定义关键词：{keywords}",
        "{count} languages available": "{count} 种语言可添加",
        "Unknown language": "未知语言",
        "Select a language to add:": "选择要添加的语言：",
        "Choose a language before adding it.": "请先选择要添加的语言。",
        "Language is already in favorites: {code}": "语言已在收藏中：{code}",
        "Added language: {name}": "已添加语言：{name}",
        "Select a language before removing.": "请先选择要移除的语言。",
        "Removed language: {name}": "已移除语言：{name}",
        "Installed bilingual packs for Blender {version}. Restart Blender, then choose zh_en or en_zh.": "已为 Blender {version} 安装双语语言包。请重启 Blender，然后选择 zh_en 或 en_zh。",
        "Uninstalled bilingual packs. Restart Blender to refresh the language list.": "已卸载双语语言包。请重启 Blender 以刷新语言列表。",
        "Could not install bilingual packs: {error}. Check Blender locale folder permissions and try again.": "无法安装双语语言包：{error}。请检查 Blender locale 文件夹权限后重试。",
        "Could not uninstall bilingual packs: {error}. Check bilingual manifest and locale folder permissions.": "无法卸载双语语言包：{error}。请检查双语清单和 locale 文件夹权限。",
        "Switched UI language to {name}": "已将界面语言切换为 {name}",
        "Default languages added to the top-bar switcher": "已将默认语言添加到顶部栏切换器",
    },
    "zh_HANT": {
        "Basic Language Switching": "基礎語言切換",
        "Advanced: Bilingual Language Packs": "進階：雙語語言包",
        "Experimental: Region Scope": "實驗性：區域範圍",
        "Enable Experimental Region Scope": "啟用實驗性區域範圍",
        "Experimental scope: disabled": "實驗性範圍：已關閉",
        "When disabled, bilingual pack installation uses the default full scope.": "關閉時，雙語包安裝將使用預設完整範圍。",
        "Install / Update Bilingual Packs": "安裝/更新雙語語言包",
        "Uninstall Bilingual Packs": "解除安裝雙語語言包",
        "Language 1": "語言 1",
        "Language 2": "語言 2",
        "Manage Languages...": "管理語言...",
        "Add Default Languages": "新增預設語言",
        "Switch Language": "切換語言",
        "Open Preferences": "開啟偏好設定",
        "Add Language": "新增語言",
        "Add a language to the top-bar switcher": "新增語言到頂部列切換器",
        "Remove Language": "移除語言",
        "Move Language": "移動語言",
        "Install Bilingual Language Pack": "安裝雙語語言包",
        "Uninstall Bilingual Language Pack": "解除安裝雙語語言包",
        "Node / Shader / Geometry Nodes": "節點 / 著色器 / 幾何節點",
        "Material / Texture": "材質 / 紋理",
        "Animation / Rigging": "動畫 / 綁定",
        "Viewport / Navigation": "視圖 / 導覽",
        "Modeling / Mesh": "建模 / 網格",
        "Sculpt / Paint": "雕刻 / 繪製",
        "Compositor / VFX": "合成器 / 視覺特效",
        "Render / Lighting": "算繪 / 燈光",
        "Custom Keywords": "自訂關鍵詞",
        "Manage languages shown in the top-bar switcher.": "管理頂部列切換器中顯示的語言。",
        "All available languages are already in favorites": "所有可用語言都已在收藏中",
        "Click button above to add languages": "點擊上方按鈕新增語言",
        "Favorites: {count}": "收藏：{count}",
        "Installs separate zh_en/en_zh languages into Blender's locale folder.": "將獨立的 zh_en/en_zh 語言安裝到 Blender 的 locale 資料夾。",
        "Backs up the languages file. Restart Blender after install or uninstall.": "會備份 languages 檔案。安裝或解除安裝後請重新啟動 Blender。",
        "Generated bilingual packs are removed automatically when this add-on is disabled.": "停用此外掛時會自動移除已產生的雙語語言包。",
        "Affects the next bilingual pack install; it does not change the current language immediately.": "影響下一次雙語包安裝；不會立即變更目前語言。",
        "Uses exact English labels. Same-name UI labels may still be included.": "使用英文標籤精確比對；同名介面標籤仍可能被包含。",
        "Installed manifest: not found": "安裝清單：未找到",
        "Installed manifest: unreadable": "安裝清單：無法讀取",
        "Installed manifest: Blender {version}, {count} keywords": "安裝清單：Blender {version}，{count} 個關鍵詞",
        "Selected regions: {count} | Custom keywords: {keywords}": "已選區域：{count} | 自訂關鍵詞：{keywords}",
        "{count} languages available": "{count} 種語言可新增",
        "Unknown language": "未知語言",
        "Select a language to add:": "選擇要新增的語言：",
        "Choose a language before adding it.": "請先選擇要新增的語言。",
        "Language is already in favorites: {code}": "語言已在收藏中：{code}",
        "Added language: {name}": "已新增語言：{name}",
        "Select a language before removing.": "請先選擇要移除的語言。",
        "Removed language: {name}": "已移除語言：{name}",
        "Installed bilingual packs for Blender {version}. Restart Blender, then choose zh_en or en_zh.": "已為 Blender {version} 安裝雙語語言包。請重新啟動 Blender，然後選擇 zh_en 或 en_zh。",
        "Uninstalled bilingual packs. Restart Blender to refresh the language list.": "已解除安裝雙語語言包。請重新啟動 Blender 以重新整理語言清單。",
        "Could not install bilingual packs: {error}. Check Blender locale folder permissions and try again.": "無法安裝雙語語言包：{error}。請檢查 Blender locale 資料夾權限後重試。",
        "Could not uninstall bilingual packs: {error}. Check bilingual manifest and locale folder permissions.": "無法解除安裝雙語語言包：{error}。請檢查雙語清單和 locale 資料夾權限。",
        "Switched UI language to {name}": "已將介面語言切換為 {name}",
        "Default languages added to the top-bar switcher": "已將預設語言新增到頂部列切換器",
    },
    "ja_JP": {
        "Basic Language Switching": "基本言語切り替え",
        "Advanced: Bilingual Language Packs": "高度: バイリンガル言語パック",
        "Experimental: Region Scope": "実験的: 領域スコープ",
        "Enable Experimental Region Scope": "実験的な領域スコープを有効化",
        "Experimental scope: disabled": "実験的スコープ: 無効",
        "When disabled, bilingual pack installation uses the default full scope.": "無効の場合、バイリンガルパックのインストールは既定の全範囲を使用します。",
        "Install / Update Bilingual Packs": "バイリンガルパックをインストール/更新",
        "Uninstall Bilingual Packs": "バイリンガルパックをアンインストール",
        "Language 1": "言語 1",
        "Language 2": "言語 2",
        "Manage Languages...": "言語を管理...",
        "Add Default Languages": "既定の言語を追加",
        "Switch Language": "言語を切り替え",
        "Open Preferences": "プリファレンスを開く",
        "Add Language": "言語を追加",
        "Add a language to the top-bar switcher": "トップバー切り替えメニューに言語を追加します",
        "Remove Language": "言語を削除",
        "Move Language": "言語を移動",
        "Install Bilingual Language Pack": "バイリンガル言語パックをインストール",
        "Uninstall Bilingual Language Pack": "バイリンガル言語パックをアンインストール",
        "Node / Shader / Geometry Nodes": "ノード / シェーダー / ジオメトリノード",
        "Material / Texture": "マテリアル / テクスチャ",
        "Animation / Rigging": "アニメーション / リギング",
        "Viewport / Navigation": "ビューポート / ナビゲーション",
        "Modeling / Mesh": "モデリング / メッシュ",
        "Sculpt / Paint": "スカルプト / ペイント",
        "Compositor / VFX": "コンポジター / VFX",
        "Render / Lighting": "レンダー / ライティング",
        "Custom Keywords": "カスタムキーワード",
        "Manage languages shown in the top-bar switcher.": "トップバーの切り替えメニューに表示する言語を管理します。",
        "All available languages are already in favorites": "利用可能な言語はすべてお気に入りに登録済みです",
        "Click button above to add languages": "上のボタンをクリックして言語を追加します",
        "Favorites: {count}": "お気に入り: {count}",
        "Installs separate zh_en/en_zh languages into Blender's locale folder.": "個別の zh_en/en_zh 言語を Blender の locale フォルダーにインストールします。",
        "Backs up the languages file. Restart Blender after install or uninstall.": "languages ファイルをバックアップします。インストールまたはアンインストール後に Blender を再起動してください。",
        "Generated bilingual packs are removed automatically when this add-on is disabled.": "このアドオンを無効にすると、生成されたバイリンガルパックは自動的に削除されます。",
        "Affects the next bilingual pack install; it does not change the current language immediately.": "次回のバイリンガルパックのインストールに影響します。現在の言語はすぐには変更されません。",
        "Uses exact English labels. Same-name UI labels may still be included.": "英語ラベルの完全一致を使用します。同名の UI ラベルが含まれる場合があります。",
        "Installed manifest: not found": "インストール情報: 見つかりません",
        "Installed manifest: unreadable": "インストール情報: 読み取れません",
        "Installed manifest: Blender {version}, {count} keywords": "インストール情報: Blender {version}、{count} 個のキーワード",
        "Selected regions: {count} | Custom keywords: {keywords}": "選択領域: {count} | カスタムキーワード: {keywords}",
        "{count} languages available": "追加可能な言語: {count}",
        "Unknown language": "不明な言語",
        "Select a language to add:": "追加する言語を選択:",
        "Choose a language before adding it.": "追加する前に言語を選択してください。",
        "Language is already in favorites: {code}": "言語は既にお気に入りにあります: {code}",
        "Added language: {name}": "言語を追加しました: {name}",
        "Select a language before removing.": "削除する前に言語を選択してください。",
        "Removed language: {name}": "言語を削除しました: {name}",
        "Installed bilingual packs for Blender {version}. Restart Blender, then choose zh_en or en_zh.": "Blender {version} 用のバイリンガルパックをインストールしました。Blender を再起動してから zh_en または en_zh を選択してください。",
        "Uninstalled bilingual packs. Restart Blender to refresh the language list.": "バイリンガルパックをアンインストールしました。言語リストを更新するには Blender を再起動してください。",
        "Could not install bilingual packs: {error}. Check Blender locale folder permissions and try again.": "バイリンガルパックをインストールできませんでした: {error}。Blender の locale フォルダー権限を確認して再試行してください。",
        "Could not uninstall bilingual packs: {error}. Check bilingual manifest and locale folder permissions.": "バイリンガルパックをアンインストールできませんでした: {error}。バイリンガル manifest と locale フォルダー権限を確認してください。",
        "Switched UI language to {name}": "UI 言語を {name} に切り替えました",
        "Default languages added to the top-bar switcher": "既定の言語をトップバー切り替えメニューに追加しました",
    },
}


def normalize_language(language_code: str | None) -> str:
    language = language_code or "en_US"
    return LANGUAGE_ALIASES.get(language, language)


def translate(text: str, language_code: str | None = None) -> str:
    language = normalize_language(language_code)
    return TRANSLATIONS.get(language, {}).get(text, text)


def tr(text: str) -> str:
    language = None
    if bpy is not None:
        try:
            language = bpy.context.preferences.view.language
        except Exception:
            language = None
    return translate(text, language)
